config/routes.rb
Pipeline::Application.routes.draw do

  get 'contact_for_deals/index'

  resources :deals do
    member do 
      get '/address',  to: 'deals#address'
      get '/property', to: 'deals#property_information'
      get '/overview', to: 'deals#overview'  
      post 'add_to_pipeline'   
      match '/remove_deal', to: 'deals#remove_from_pipeline', via: :delete   
    end
    get '/photos', to: 'image_galleries#index'
    resources :image_galleries
    resources :important_docs
    resources :important_dates
    get '/contacts', to: 'contact_for_deals#index'   
    resources :contact_for_deals 
  end

  resources :contacts
  
  


  resources :conversations do
    resources :messages
  end






  resources :users, :only => :show

  devise_for :users, :controllers => { :registrations => "registrations" }, 
             :skip => [:sessions, :passwords] 
 
  devise_scope :user do
    get  '/register', to: 'devise/registrations#new', as: :register
    # post '/register', to: 'devise/registrations#create', as: :user_registration
    # put  '/register', to: 'devise/registrations#edit', as: :registration
    get  '/dashboard/profile/edit', to: 'devise/registrations#edit', as: :edit

    get  '/login', to: 'devise/sessions#new', as: :new_user_session    
    post '/login', to: 'devise/sessions#create', as: :user_session  
    get  '/logout', to: 'devise/sessions#destroy', as: :logout
    
    get  '/password/new', to: 'devise/passwords#new', as: :new_user_password
    post '/password/new', to: 'devise/passwords#create', as: :user_password
  end  

  get '/market', to: 'market_places#index', as: :market

  root to: "static_pages#home"
  
end

app/views/layouts/aside/_brokerform_aside.html.haml
.bg-white{:style => "position:fixed; width:239px;"}
  .text-muted-extra.m-t-sm.text-xs.hidden-nav-xs.padder.text-u-c.font-bold
    Basic Information
  %ul.nav.nav-main{"data-ride" => "collapse"}
    %li
      = link_to property_deal_path(@deal) do
        Property Information
        %span.pull-right.text-danger
          %i.i.i-plus.icon
    %li
      = link_to address_deal_path(@deal) do
        Property Address
        %span.pull-right.text-danger
          %i.i.i-plus.icon
  .text-muted-extra.text-xs.hidden-nav-xs.padder.m-t-sm.text-u-c.font-bold
    Description
  %ul.nav.nav-main{"data-ride" => "collapse"}
    %li
      = link_to overview_deal_path(@deal) do
        Overview
        %span.pull-right.text-danger
          %i.i.i-plus.icon
    %li
      = link_to deal_photos_path(@deal) do
        Photos
        %span.pull-right.text-danger
          %i.i.i-plus.icon
  .text-muted-extra.text-xs.hidden-nav-xs.padder.m-t-sm.text-u-c.font-bold
    Extras
  %ul.nav.nav-main{"data-ride" => "collapse"}
    %li
      = link_to deal_important_docs_path(@deal) do
        Important Docs
        %span.pull-right.text-danger
          %i.i.i-plus.icon
    %li
      = link_to deal_important_dates_path(@deal) do
        Important Dates
        %span.pull-right.text-danger
          %i.i.i-plus.icon
    %li
      = link_to deal_contacts_path(@deal) do
        Contacts
        %span.pull-right.text-danger
          %i.i.i-plus.icon

app/views/layouts/aside/_deals_index.html.haml
%h4.text-u-c Filters
.form-group
  %label City
  %button.btn.btn-sm.btn-default.btn-block.dropdown-toggle{"data-toggle" => "dropdown", :style => "padding:7px 16px;"}
    %span.dropdown-label.pull-left{"data-placeholder" => "Please select"} City
    .pull-right
      %span.caret{:style => "margin-left:30px;"}
  %ul.dropdown-menu.dropdown-select
    %li
      %a{:href => "#"}
    %li
      %a{:href => "#"}
.form-group
  %label Owner
  %button.btn.btn-sm.btn-default.btn-block.dropdown-toggle{"data-toggle" => "dropdown", :style => "padding:7px 16px;"}
    %span.dropdown-label.pull-left{"data-placeholder" => "Please select"} Owner
    .pull-right
      %span.caret{:style => "margin-left:30px;"}
  %ul.dropdown-menu.dropdown-select
    %li
      %a{:href => "#"}
    %li
      %a{:href => "#"}
.form-group
  %label Space Type
  %button.btn.btn-sm.btn-default.btn-block.dropdown-toggle{"data-toggle" => "dropdown", :style => "padding:7px 16px;"}
    %span.dropdown-label.pull-left{"data-placeholder" => "Please select"} Space Type
    .pull-right
      %span.caret{:style => "margin-left:30px;"}
  %ul.dropdown-menu.dropdown-select
    %li
      %a{:href => "#"}
    %li
      %a{:href => "#"}
.form-group
  %label Most Active User
  %button.btn.btn-sm.btn-default.btn-block.dropdown-toggle{"data-toggle" => "dropdown", :style => "padding:7px 16px;"}
    %span.dropdown-label.pull-left{"data-placeholder" => "Please select"} Most Active User
    .pull-right
      %span.caret{:style => "margin-left:30px;"}
  %ul.dropdown-menu.dropdown-select
    %li
      %a{:href => "#"}
    %li
      %a{:href => "#"}
.form-group
  %label Status
  %button.btn.btn-sm.btn-default.btn-block.dropdown-toggle{"data-toggle" => "dropdown", :style => "padding:7px 16px;"}
    %span.dropdown-label.pull-left{"data-placeholder" => "Please select"} Status
    .pull-right
      %span.caret{:style => "margin-left:30px;"}
  %ul.dropdown-menu.dropdown-select
    %li
      %a{:href => "#"}
    %li
      %a{:href => "#"}
%label Size (SF)
.row
  .col-md-5
    %input.form-control{:type => "text"}/
  .col-md-2
    to
  .col-md-5
    %input.form-control{:type => "text"}/
%label Size (SF)
.row
  .col-md-5
    %input.form-control{:type => "text"}/
  .col-md-2
    to
  .col-md-5
    %input.form-control{:type => "text"}/
%label Size (SF)
.row
  .col-md-5
    %input.form-control{:type => "text"}/
  .col-md-2
    to
  .col-md-5
    %input.form-control{:type => "text"}/
%label Size (SF)
.row
  .col-md-5
    %input.form-control{:type => "text"}/
  .col-md-2
    to
  .col-md-5
    %input.form-control{:type => "text"}/
%label Size (SF)
.row
  .col-md-5
    %input.form-control{:type => "text"}/
  .col-md-2
    to
  .col-md-5
    %input.form-control{:type => "text"}/

app/views/layouts/aside/_market_places.html.haml
%h4.text-u-c Filters
.form-group
  %label City
  %button.btn.btn-sm.btn-default.btn-block.dropdown-toggle{"data-toggle" => "dropdown", :style => "padding:7px 16px;"}
    %span.dropdown-label.pull-left{"data-placeholder" => "Please select"} City
    .pull-right
      %span.caret{:style => "margin-left:30px;"}
  %ul.dropdown-menu.dropdown-select
    %li
      %a{:href => "#"}
    %li
      %a{:href => "#"}
.form-group
  %label Brokers
  %button.btn.btn-sm.btn-default.btn-block.dropdown-toggle{"data-toggle" => "dropdown", :style => "padding:7px 16px;"}
    %span.dropdown-label.pull-left{"data-placeholder" => "Please select"} Brokers
    .pull-right
      %span.caret{:style => "margin-left:30px;"}
  %ul.dropdown-menu.dropdown-select
    %li
      %a{:href => "#"}
    %li
      %a{:href => "#"}
.form-group
  %label Space Type
  %button.btn.btn-sm.btn-default.btn-block.dropdown-toggle{"data-toggle" => "dropdown", :style => "padding:7px 16px;"}
    %span.dropdown-label.pull-left{"data-placeholder" => "Please select"} Space Type
    .pull-right
      %span.caret{:style => "margin-left:30px;"}
  %ul.dropdown-menu.dropdown-select
    %li
      %a{:href => "#"}
    %li
      %a{:href => "#"}
.form-group
  %label Status
  %button.btn.btn-sm.btn-default.btn-block.dropdown-toggle{"data-toggle" => "dropdown", :style => "padding:7px 16px;"}
    %span.dropdown-label.pull-left{"data-placeholder" => "Please select"} Status
    .pull-right
      %span.caret{:style => "margin-left:30px;"}
  %ul.dropdown-menu.dropdown-select
    %li
      %a{:href => "#"}
    %li
      %a{:href => "#"}
%label Size (SF)
.row
  .col-md-5
    %input.form-control{:type => "text"}/
  .col-md-2
    to
  .col-md-5
    %input.form-control{:type => "text"}/