config/routes.rb
Pipeline::Application.routes.draw do

  get 'contact_for_deals/index'

  resources :deals do
    member do 
      get '/address',  to: 'deals#address'
      get '/property', to: 'deals#property_information'
      get '/overview', to: 'deals#overview'  
      post 'add_to_pipeline'   
      match '/remove_deal', to: 'deals#remove_from_pipeline', via: :delete   
    end
    get '/photos', to: 'image_galleries#index'
    resources :image_galleries
    resources :important_docs
    resources :important_dates
    get '/contacts', to: 'contact_for_deals#index'   
    resources :contact_for_deals 
  end

  resources :contacts
  
  


  resources :conversations do
    resources :messages
  end






  resources :users, :only => :show

  devise_for :users, :controllers => { :registrations => "registrations" }, 
             :skip => [:sessions, :passwords] 
 
  devise_scope :user do
    get  '/register', to: 'devise/registrations#new', as: :register
    # post '/register', to: 'devise/registrations#create', as: :user_registration
    # put  '/register', to: 'devise/registrations#edit', as: :registration
    get  '/dashboard/profile/edit', to: 'devise/registrations#edit', as: :edit

    get  '/login', to: 'devise/sessions#new', as: :new_user_session    
    post '/login', to: 'devise/sessions#create', as: :user_session  
    get  '/logout', to: 'devise/sessions#destroy', as: :logout
    
    get  '/password/new', to: 'devise/passwords#new', as: :new_user_password
    post '/password/new', to: 'devise/passwords#create', as: :user_password
  end  

  get '/market', to: 'market_places#index', as: :market

  root to: "static_pages#home"
  
end

app/views/layouts/_aside.html.haml
/ aside
%aside#aside.app-aside.hidden-xs.bg-offwhite{:style => "position:fixed; height:100%;"}
  .aside-wrap
    .navi-wrap
      / nav
      %nav.navi.clearfix{:style => "padding:20px", "ui-nav" => ""}
        = add_new_deal_btn
        %ul.nav
          %li.hidden-folded.m-b-sm.text-xs.nav-sm-title
            %span Menu
          %li
            = link_to root_path, class: "auto", title: "Dashboard" do
              %i.i.i-statistics
              %span Dashboard
          %li
            %a.auto{:href => ""}
              %i.i.i-mail2
              %span Inbox
          %li
            = link_to market_path, class: "auto", title: "Market" do
              %b.badge.bg-info.pull-right= Deal.where(publish: true).count
              %i.i.i-chart
              %span Market
          %li
            = link_to deals_path, class: "auto", title: "My Pipeline" do
              %i.i.i-paperplane
              %span My Pipeline
          %li
            %a.auto{:href => ""}
              %i.i.i-calendar
              %span Calendar
          %li
            = link_to contacts_path, class: "auto", title: "Contacts" do
              %i.i.i-bubble
              %span Contacts
          %li.hidden-folded.m-t-lg.m-b-sm.text-xs.nav-sm-title
            %span Settings
          %li
            = link_to "#", class: "auto", title: "Dashboard" do
              %i.i.i-statistics
              %span Account
          %li
            %a.auto{:href => ""}
              %i.i.i-mail2
              %span Integration
          %li
            = link_to "#", class: "auto", title: "Market" do
              %i.i.i-chart
              %span Notification
          %li
            = link_to "#", class: "auto", title: "My Pipeline" do
              %i.i.i-paperplane
              %span Billing
      / nav
/ / aside

app/views/layouts/_aside_xs.html.haml
%aside.bg-dark.lter.b-r.aside.hidden-print.nav-xs
  %section.vbox
    %nav.nav-primary.hidden-xs
    - unless params[:action] == "index" && params[:controller] == "deals"
      %footer.footer.hidden-xs.no-padder.text-center-nav-xs
        %a#toggle.btn.btn-icon.icon-muted.btn-inactive.m-l-xs.m-r-xs.active{"data-toggle" => "class:nav-xs", :href => "#nav"}
          %i.i.i-circleleft.text
          %i.i.i-circleright.text-active

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key} bold"}
    = value

app/views/layouts/_footer.html.haml
:javascript
  // Bootstrap wysihtml5 editor     
  $('.wysihtml5').each(function(i, elem) {
    $(elem).wysihtml5({
      "font-styles": false, //Font styling, e.g. h1, h2, etc. Default true
      "emphasis": false, //Italics, bold, etc. Default true
      "lists": false, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
      "html": false, //Button which allows you to edit the generated HTML. Default false
      "link": false, //Button to insert a link. Default true
      "image": false, //Button to insert an image. Default true,
      "color": false //Button to change color of font 
      
    });
    
   
  });




  $(".wysihtml5-toolbar .btn").addClass('btn-default btn-sm');

  // Image preview before upload
  var preview = $(".upload-preview-options img");

      $("#lefile").change(function(event){
           var input = $(event.currentTarget);
           var file = input[0].files[0];
           var reader = new FileReader();
           reader.onload = function(e){
               image_base64 = e.target.result;
               preview.attr("src", image_base64);
           };
           reader.readAsDataURL(file);
           preview.addClass('preview-img-border');

          $('#uploadimage').css('width', '115px').css('height', '115px');  
          $('#pageimage').css('width', '150px').css('height', '150px');  


      });


      
    // Disable submit btn on click
      $('input[type="submit"').click(function() {
          $(this).addClass("disabled");
      });

  // Toggle second left sidebar
  $('#toggle').click(function() {
  $('#aside_toggle').toggle();
  });

  $(window).resize(function() {
      var width = $(window).width() - 440;
      $("#fixedheader").css("width", width);
  });
  var width = $(window).width() - 440;
  $("#fixedheader").css("width", width);

  $(window).resize(function() {
      var width = $(window).width() - 440;
      $("#fixedfooter").css("width", width);
  });
  var width = $(window).width() - 440;
  $("#fixedfooter").css("width", width);

  $(window).resize(function() {
      var width = $(window).width() - 200;
      $("#fixedheader2").css("width", width);
  });
  var width = $(window).width() - 200;
  $("#fixedheader2").css("width", width);

app/views/layouts/_head.html.haml
%head
  %title Pipeline - Demo
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tags
  %meta{:content => "#{user_signed_in? ? current_user.id : ""}", :name => "user-id"}/

app/views/layouts/_header.html.haml
%body
  .app.app-header-fixed
    / header
    %header#header.app-header.navbar{:role => "menu"}
      / navbar header
      / / navbar header
      / navbar collapse
      .collapse.pos-rlt.navbar-collapse.bg-white.b-b.box-shadow
        / buttons
        .nav.navbar-nav.hidden-xs
          %a.navbar-brand.text-lt{:href => "#/"}
            %i.i.i-chat2.text-info{:style => "position:relative; top:3px;"}
        / / buttons
        / nabar right
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %i.icon-bell.fa-fw
                %span.visible-xs-inline Notifications
                %span.badge.badge-sm.up.bg-danger.pull-right-xs 2
              / dropdown
              .dropdown-menu.w-xl.animated.fadeInUp
                .panel.bg-white
                  .panel-heading.b-light.bg-light
                    %strong
                      You have
                      %span 2
                      notifications
                  .list-group
                    %a.media.list-group-item{:href => ""}
                      %span.pull-left.thumb-sm
                        = image_tag('a5.jpg')
                      %span.media-body.block.m-b-none
                        Use awesome animate.css
                        %br/
                        %small.text-muted 10 minutes ago
                    %a.media.list-group-item{:href => ""}
                      %span.media-body.block.m-b-none
                        1.0 initial released
                        %br/
                        %small.text-muted 1 hour ago
                  .panel-footer.text-sm
                    %a.pull-right{:href => ""}
                      %i.fa.fa-cog
                    %a{"data-toggle" => "class:show animated fadeInRight", :href => "#notes"} See all the notifications
              / / dropdown
            %li.dropdown
              %a.dropdown-toggle.clear{"data-toggle" => "dropdown", :href => "#"}
                %span.thumb-sm.avatar.pull-right.m-t-n-sm.m-b-n-sm.m-l-sm
                  = image_tag('a5.jpg')
                  %i.on.md.b-white.bottom
                %span.hidden-sm.hidden-md= full_name
                %i.i.i-arrow-down5
              / dropdown
              %ul.dropdown-menu.animated.fadeInRight.w
                %li.wrapper.b-b.m-b-sm.bg-light.m-t-n-xs
                  %div
                    %p 300mb of 500mb used
                  .progress.progress-xs.m-b-none.dker
                    .progress-bar.progress-bar-info{"data-original-title" => "50%", "data-toggle" => "tooltip", :style => "width: 50%"}
                %li
                  %a{:href => ""}
                    %span.badge.bg-danger.pull-right 30%
                    %span Settings
                %li
                  %a{"ui-sref" => "app.page.profile"} Profile
                %li
                  %a{"ui-sref" => "app.docs"}
                    %span.label.bg-info.pull-right new
                    Help
                %li.divider
                %li
                  = link_to "Logout", logout_path
              / / dropdown
          - else
            %li= link_to "Login", new_user_session_path
            %li= link_to "Register", register_path
        / / navbar right
      / / navbar collapse
    / / header

app/views/layouts/application.html.haml
!!!
%html
  %body
    = render 'layouts/head'
    = render 'layouts/header'
    = render 'layouts/flash'
    = render 'layouts/aside'
    #content.app-content{:role => "main"}
      .app-content-body
        .hbox.hbox-auto-xs.hbox-auto-sm{"ng-init" => "\n            app.settings.asideFolded = false; \n            app.settings.asideDock = false;\n          "}
          / main
          .col
            = yield
          .col.w-md.bg-white-only.b-l.bg-auto.no-border-xs
            .wrapper-md
              .m-b-sm.text-md Chat
              %ul.list-group.no-bg.no-borders.pull-in
                - User.all.each do |u|
                  %li.list-group-item
                    %a.pull-left.thumb-sm.avatar.m-r{:herf => ""}
                      = image_tag('a4.jpg', class: "img-circle")
                      %i.on.b-white.bottom
                    .clear
                      %div
                        = link_to u.firstname + " " +  u.lastname, "#", class: "start-conversation", |
                          "data-sid" => current_user.id, "data-rip" => u.id                          |
                      %small.text-muted East Gate Capital LLC
              .text-center
                %a.btn.btn-sm.btn-primary.padder-md.m-b{:href => ""} More Connections
      = render 'layouts/footer'

app/views/layouts/deals.html.haml
!!!
%html
  %body
    = render 'layouts/head'
    = render 'layouts/header'
    = render 'layouts/flash'
    = render 'layouts/aside'
    #content.app-content{:role => "main"}
      #fixedheader2.wrapper.bg-white.b-b.box-shadow.fixedheader
        .pull-left
          %span.bold.text-muted.deals-breadcrumb
            Deals / #{@deal.property_name}
        .btn-toolbar
          = form_for(@deal) do |f|
            = f.hidden_field :publish, value: true
            = f.submit "Publish", class: "btn btn-sm btn-info btn-shadow pull-right"
      .hbox.hbox-auto-xs.hbox-auto-sm{"ng-controller" => "MailCtrl", :style => "padding-top:61px"}
        .col.w-md.bg-white.b-r.bg-auto
          = render 'layouts/aside/brokerform_aside'
        .col
          = yield
    = render 'layouts/footer'

app/views/layouts/deals_new.html.haml
!!!
%html
  %body
    = render 'layouts/head'
    %section.vbox
      - flash.each do |type, message|
        #alert-fadeout{:class => "alert #{flash_class type}"}
          %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
          = message
      %section
        %section.hbox.stretch
          %section#content
            %section.hbox.stretch
              %section
                %section.vbox= yield
                / end vbox
              / end section
            / end hbox stretch
          / end id content
        / end hbox stretch
      / end section
    / end vbox
    = render 'layouts/footer'

app/views/layouts/devise.html.haml
!!!
%html.white-bg
  %body
    = render 'layouts/head'
    #wrapper
      - flash.each do |type, message|
        #alert-fadeout{:class => "alert #{flash_class type}"}
          %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
          = message
      #page
        #content_container
          #content
            = link_to root_path do
              %h3.center Pipeline
            = yield
    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/layouts/market.html.haml
!!!
%html.app-fluid
  %body
    = render 'layouts/head'
    %section.hbox.stretch
      = render 'layouts/aside_xs'
      %section#content
        %section.hbox.stretch
          %section
            %section.vbox
              = render 'layouts/header'
              = render 'layouts/flash'
              %section.hbox.stretch
                %aside.bg-white.lt.b-r.b-light.aside-lg.hidden-print
                  %section.vbox
                    %section.w-f.scrollable
                      .slim-scroll{"data-disable-fade-out" => "true", "data-distance" => "0", "data-height" => "auto", "data-railopacity" => "0.2", "data-size" => "10px"}
                        / nav
                        %nav.nav-primary.hidden-xs
                          12 Properties from 5 Brokers
                        / / nav
                = yield
        %a.hide.nav-off-screen-block{"data-target" => "#nav", "data-toggle" => "class:nav-off-screen", :href => "#"}
    :javascript
      $(document).ready(function() {
        $('#toggle').click(function() {
          $('#aside_toggle').toggle();
        });
      });

app/views/layouts/static_pages.html.haml
!!!
%html
  %body
    = render 'layouts/head'
    = render 'layouts/header'
    = render 'layouts/flash'
    - if user_signed_in?
      = render 'layouts/aside'
    #content.app-content{:role => "main"}
      = yield
    = render 'layouts/footer'